services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
    - HOST=db
    - USER=ordent
    - PASSWORD=ordent1234!
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=ordent1234!
      - POSTGRES_USER=ordent
  nginx:
    image: nginx:1.23-alpine
    depends_on:
      - web
    container_name: nginx-odoo
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./cert:/etc/nginx/cert
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443