services:
  web:
    image: odoo:16.0
    ports:
      - "8069:8069"
    volumes:
      - /data/container/data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  nginx:
    image: nginx:1.23-alpine
    depends_on:
      - web
    container_name: nginx-odoo
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./cert:/etc/nginx/cert
    ports:
      - 80:80
      - 443:443